### ISSUE TITLE
Console config management setup fails with defaults

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/acm-policy-controller-library#27]
The current [method to install policy controller](https://cloud.google.com/anthos-config-management/docs/how-to/installing-policy-controller#console) with default settings on a GKE autopilot cluster with public endpoint appears to have errors on git-sync. The console page shows an error and prompted executing the following command to troubleshoot:

`kubectl logs -n config-management-system -l configsync.gke.io/reconciler=root-reconciler -c git-sync`

> I0913 17:33:41.198160      13 main.go:940] "level"=0 "msg"="git root exists and is not empty (previous crash?), cleaning up" "path"="/repo/source"
> I0913 17:33:41.297645      13 main.go:611] "level"=2 "msg"="removing path recursively" "path"="/repo/source/error.json" "isDir"=false
> I0913 17:33:41.297836      13 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b main --depth 1 https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022 /repo/source"
> E0913 17:33:49.699769      13 main.go:539] "msg"="error syncing repo, will retry" "error"="Run(git clone -v --no-checkout -b main --depth 1 https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022 /repo/source): exit status 128: { stdout: "", stderr: "Cloning into '/repo/source'...\nfatal: repository 'https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022/' not found" }" "failCount"=6 "waitTime"=15000000000
> I0913 17:34:04.703169      13 main.go:527] "level"=1 "msg"="syncing repo"
> I0913 17:34:04.703926      13 main.go:934] "level"=0 "msg"="cloning repo" "origin"="https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022" "path"="/repo/source"
> I0913 17:34:04.703962      13 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b main --depth 1 https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022 /repo/source"
> I0913 17:34:04.897614      13 main.go:940] "level"=0 "msg"="git root exists and is not empty (previous crash?), cleaning up" "path"="/repo/source"
> I0913 17:34:04.897762      13 main.go:611] "level"=2 "msg"="removing path recursively" "path"="/repo/source/error.json" "isDir"=false
> I0913 17:34:04.897865      13 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b main --depth 1 https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022 /repo/source"

Testing shows that `git clone -v --no-checkout -b main --depth 1 https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022 ./` return "not found" error.

**Comment by apeabody** [comment]
Hi @hilliao - Thanks again for reaching out and connecting directly.  This should now be resolved.  For your existing cluster you may need to re-select the repository under Config Sync.  Cheers!
