### ISSUE TITLE
Issue with `1.1.2_asm-sidecar-injection` when using Istio CNI

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/acm-policy-controller-library#28]
When using the Istio CNI (ASM's recommended approach), the `istio-cni-node` `Daemonset` in the `kube-system` `Namespace` generates a `Pod` with the annotation: `sidecar.istio.io/inject: "false"`. This generates an issue with the `Constraint` `1.1.2_asm-sidecar-injection` which for now just excludes the `istio-system` `Namespace` (makes sense for the `istiod` `Pod`).

Could you please also add by default the exclusion of the `kube-system` `Namespace`?

**Comment by apeabody** [comment]
Hi @mathieu-benoit,

Thanks for reaching out!  I have some great news that this will be included in this upcoming update to the bundle: https://github.com/GoogleCloudPlatform/acm-policy-controller-library/pull/32

**Comment by mathieu-benoit** [comment]
Wonderful, thanks!
