### ISSUE TITLE
Confusion with the `GoogleCloudPlatform/acm-essentials` repo

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/acm-policy-controller-library#39]
In this doc https://cloud.google.com/anthos-config-management/docs/how-to/using-cis-k8s-benchmark#before_you_begin, at the bullet point 5 we are mentioning this other repo: https://github.com/GoogleCloudPlatform/acm-essentials.

Is this other repo still maintained? Should we deprecate it? What's the differences with the https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/cis-k8s-v1.5.1 bundle?

**Comment by apeabody** [comment]
Thanks for reaching out @mathieu-benoit!  The [documentation](https://cloud.google.com/anthos-config-management/docs/how-to/using-cis-k8s-benchmark#before_you_begin) has be updated to remove point 5, as the source of bundles is https://github.com/GoogleCloudPlatform/acm-policy-controller-library.  The other repo was equivalent to https://github.com/GoogleCloudPlatform/acm-policy-controller-library/tree/main/bundles/policy-essentials-v2022.
