### ISSUE TITLE
Where to find "Pod Security Standards Restricted v2022"

### ISSUE THREAD

**Issue by lesaux** [GoogleCloudPlatform/acm-policy-controller-library#51]
Hello,
The new GKE security dashboards mention this new "Pod Security Standards Restricted v2022" compliance standard.
Would anyone know where I can find it?
I found a preview of the PCI-DSS one in a branch of this repo, but I can't seem to find this one.

**Comment by apeabody** [comment]
Hi @lesaux - The Pod Security Standards Restricted policy bundle is now posted!  I also recommend the new documentation at: https://cloud.google.com/anthos-config-management/docs/how-to/using-pss-restricted
