### ISSUE TITLE
Need help: 5.3.2_require-namespace-network-policies

### ISSUE THREAD

**Issue by lesaux** [GoogleCloudPlatform/acm-policy-controller-library#65]
How does one create a namespace once this constraint is enabled?

Is there a way to create a new namespace and its networkpolicy in one operation with config sync?

**Comment by apeabody** [comment]
Hi @lesaux - The default bundle enforcementAction is `dryrun` which will permit admissions and report as an audit violation.  If you are running in `deny`, there are a couple options, one might be to temporarily switch the enforcementAction to `warn` and then back to `deny` once the change is complete.

For example:
```
kubectl get k8srequirenamespacenetworkpolicies/cis-k8s-v1.5.1-require-namespace-network-policies -o json | jq '.spec.enforcementAction="warn"' | kubectl apply -f -
```
Apply Namespace and NetworkPolicy
```
kubectl get k8srequirenamespacenetworkpolicies/cis-k8s-v1.5.1-require-namespace-network-policies -o json | jq '.spec.enforcementAction="deny"' | kubectl apply -f -
```

**Comment by lesaux** [comment]
This is helpful, thank you @apeabody.
